name: Release

on: push

env:
  GH_TOKEN: ${{ github.token }}
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    #   - name: Check out Git repository
    #     uses: actions/checkout@v3
    #     with:
    #       submodules: "recursive"

      - name: Print Env
        run: echo "$env:GH_TOKEN"
